### PR TITLE
fix: handle non-default formats of array for query parameters

### LINKED ISSUE #52: Handle non-default stringifying of arrays in query
[Code responsible for stringifying query params](https://github.com/HLTech/pact-gen-ts/blob/67c3b589b03c26af879b04f497d3b1af9b794a95/src/core/interaction-creator.ts#L115) does not give an option to use other arrayFormat than default. This sometimes leads to being unable to generate pacts that reflect the way application calls an endpoint. 

I think current API for defining query could be enhanced to something of following format: 
```
/** 
* @pact-query 
* @query-array-format: comma // optional param, default is unchanged
*/`
const query = {
  ...
}
```

What do you guys think about it?

### PR DESCRIPTION
**Pull request by Fiszcz**
Resolves #52

### CODE REVIEW

File: src/core/interaction-creator.ts [hunk 1]
```diff
@@ -112,7 +112,7 @@ export class InteractionCreator {
             const basicTypeRepresentationOfRequestBody = getTypeRepresentation(queryElementType, this.sourceFile);
             const exampleRepresentationOfQueryObject = changeObjectRepresentationIntoExample(basicTypeRepresentationOfRequestBody);
             return {
-                query: qs.stringify(exampleRepresentationOfQueryObject),
+                query: qs.stringify(exampleRepresentationOfQueryObject, {arrayFormat: this.provider.queryArrayFormat || 'brackets'}),
```
Comment (crpc) [inline src/core/interaction-creator.ts:115]: this is different to default arrayFormat of qs.striginfy (as visible on some snapshots in diff). Default value is `indices` - could you change our default to match qs.stringify default?
